name: Run Python examples

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'
env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
  GH_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}

jobs:
  test_examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        release: [ stable ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Remove driver directories Windows
      if: matrix.os == 'windows-latest'
      run: |
        rm "$env:ChromeWebDriver" -r -v
        rm "$env:EdgeWebDriver" -r -v
        rm "$env:GeckoWebDriver" -r -v
    - name: Remove driver directories Non-Windows
      if: matrix.os != 'windows-latest'
      run: |
        sudo rm -rf $CHROMEWEBDRIVER $EDGEWEBDRIVER $GECKOWEBDRIVER
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 &
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies stable
      if: matrix.release == 'stable'
      working-directory: ./
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script
      run: |
        python main.py  # Replace with your actual script name
